/* UK Facts Kiosk — content data */

window.UK_DATA = {

  /* ===== map regions for the explainer ===== */
  regions: {
    england:   { label: "England",   capital: "London",     country: true },
    scotland:  { label: "Scotland",  capital: "Edinburgh",  country: true },
    wales:     { label: "Wales",     capital: "Cardiff",    country: true },
    nireland:  { label: "Northern Ireland", capital: "Belfast", country: true },
    ireland:   { label: "Republic of Ireland", capital: "Dublin", country: true, separate: true }
  },

  /* explainer steps — diagram morphs between these */
  explainerSteps: [
    {
      title: "Meet the islands!",
      narrator: "These bits of land are where our story happens. Two big islands and lots of little ones. Tap NEXT to keep going!",
      highlight: ["england","scotland","wales","nireland","ireland"],
      label: "British Isles"
    },
    {
      title: "This is the British Isles",
      narrator: "ALL of these islands together are called the British Isles. That includes the Republic of Ireland too — they are their own country!",
      highlight: ["england","scotland","wales","nireland","ireland"],
      shade: "british-isles",
      label: "British Isles"
    },
    {
      title: "This is Great Britain",
      narrator: "Great Britain is just the BIG island. England, Scotland and Wales all share it like flatmates sharing a house.",
      highlight: ["england","scotland","wales"],
      shade: "great-britain",
      label: "Great Britain"
    },
    {
      title: "This is the United Kingdom",
      narrator: "The UK is England, Scotland, Wales AND Northern Ireland — four countries that all share a king and a parliament.",
      highlight: ["england","scotland","wales","nireland"],
      shade: "united-kingdom",
      label: "United Kingdom"
    },
    {
      title: "Four countries, one team",
      narrator: "Each country has its own flag, its own capital and even its own football team! But together they make up the UK.",
      highlight: ["england","scotland","wales","nireland"],
      shade: "united-kingdom",
      showCapitals: true,
      label: "United Kingdom"
    }
  ],

  /* ===== facts shuffler — 45 facts ===== */
  facts: [
    { cat: "Place",     ill: "bigben",     title: "Big Ben isn't the clock!",
      body: "The famous clock tower at Parliament is called the Elizabeth Tower. Big Ben is actually the giant BELL inside it. Sneaky, eh?" },
    { cat: "Invention", ill: "phone",      title: "The telephone, ringing from Scotland",
      body: "Alexander Graham Bell, born in Edinburgh, invented the telephone in 1876. Imagine a world before phone calls!" },
    { cat: "Music",     ill: "guitar",     title: "The Beatles started in Liverpool",
      body: "Four lads from a rainy port city became the most famous band on the planet. Not bad for a Tuesday." },
    { cat: "People",    ill: "pencil",     title: "Roald Dahl wrote in a shed",
      body: "The author of Charlie and the Chocolate Factory wrote his books inside a tiny garden shed in Buckinghamshire." },
    { cat: "Food",      ill: "chips",      title: "Fish & chips: 160 years old",
      body: "Britain's favourite takeaway has been wrapped in paper since the 1860s. Add salt, vinegar, and an opinion." },
    { cat: "Place",     ill: "stones",     title: "Stonehenge is OLDER than the pyramids",
      body: "Those mysterious stones in Wiltshire were stood up around 5,000 years ago. Nobody is totally sure how. Or why." },
    { cat: "Invention", ill: "web",        title: "The World Wide Web was a British idea",
      body: "Sir Tim Berners-Lee invented the web in 1989 while working in a lab. Yes — the web you're using now." },
    { cat: "People",    ill: "crown",      title: "Queen Elizabeth II reigned for 70 years",
      body: "Longer than any other British monarch. She met 15 different Prime Ministers in her lifetime!" },
    { cat: "Place",     ill: "tube",       title: "London Underground is 160+ years old",
      body: "The Tube opened in 1863 and was the world's first underground railway. Mind the gap!" },
    { cat: "Animal",    ill: "raven",      title: "Ravens guard the Tower of London",
      body: "Legend says if the ravens ever leave, the kingdom will fall. So they get fed biscuits to keep them happy." },
    { cat: "Food",      ill: "tea",        title: "Tea bags? Not British. Tea love? Yes.",
      body: "The British drink about 100 MILLION cups of tea a day. That's a LOT of biscuit dunking." },
    { cat: "Music",     ill: "bagpipes",   title: "Bagpipes blare in Scotland",
      body: "These wheezy, wonderful instruments have been played for hundreds of years at weddings, parades and battles." },
    { cat: "People",    ill: "shakespeare",title: "Shakespeare made up 1,700 words",
      body: "Words like 'eyeball', 'lonely' and 'gossip' came from his plays. He basically invented English homework." },
    { cat: "Animal",    ill: "sheep",      title: "Wales has more sheep than people",
      body: "There are roughly 3 sheep for every person in Wales. They are very chatty (the sheep, not the people)." },
    { cat: "Food",      ill: "chocolate",  title: "Chocolate bars came from Bristol",
      body: "Fry's of Bristol made the very first solid chocolate bar in 1847. Before that? Just hot chocolate. Tragic." },
    { cat: "Place",     ill: "waves",      title: "The Giant's Causeway",
      body: "On Northern Ireland's coast, 40,000 wonky stone columns step into the sea. Made by lava, not by giants. Probably." },
    { cat: "Music",     ill: "microphone", title: "Glastonbury: a music festival in a field",
      body: "Every summer over 200,000 people pile into a Somerset farm to hear bands and lose their wellies in mud." },
    { cat: "People",    ill: "finch",      title: "Charles Darwin and his finches",
      body: "This British scientist worked out how living things evolve, sparked by some little birds in the Galápagos." },
    { cat: "Invention", ill: "mower",      title: "The lawn mower! Edwin Budding, 1830",
      body: "Before this, posh gardens needed a flock of sheep or a small army with scissors. True story." },
    { cat: "Food",      ill: "breakfast",  title: "The full English breakfast",
      body: "Eggs, beans, toast, bacon, sausages, mushrooms, tomato AND black pudding. A plate of pure morning chaos." },
    { cat: "Place",     ill: "volcano",    title: "Edinburgh has an extinct volcano",
      body: "Arthur's Seat is a 350-million-year-old volcano right in the middle of Scotland's capital. Do not poke it." },
    { cat: "Invention", ill: "train",      title: "The steam train chugged in",
      body: "Engineer George Stephenson built 'Rocket' in 1829 — the train that helped change the whole world." },
    { cat: "Music",     ill: "trumpet",    title: "Adele, Ed Sheeran, David Bowie",
      body: "British music has shaped pop, punk, rock and grime. The radio would be VERY quiet without these islands." },
    { cat: "Animal",    ill: "squirrel",   title: "Red squirrels in Scotland",
      body: "The native red squirrels mostly live in Scotland and bits of Wales. Bushy tails and very judgemental faces." },
    { cat: "People",    ill: "computer",   title: "Ada Lovelace, the first coder",
      body: "In the 1840s, this English mathematician wrote the world's first computer program — for a computer that didn't quite exist yet." },
    { cat: "Place",     ill: "mountain",   title: "Snowdon — Wales's tallest peak",
      body: "Yr Wyddfa stands 1,085m above the sea. You can walk up it OR catch a little train. We won't judge." },
    { cat: "Food",      ill: "pie",        title: "Sunday roast",
      body: "Roast beef, gravy, roasted potatoes and a giant Yorkshire pudding. The official meal of having a nap after." },
    { cat: "Invention", ill: "penicillin", title: "Penicillin saved millions",
      body: "Scotsman Alexander Fleming spotted mould killing germs in 1928 — and accidentally invented modern medicine." },
    { cat: "Place",     ill: "lake",       title: "The Lake District",
      body: "A wrinkly bit of north-west England full of poets, sheep and lakes you can swim in if you're brave." },
    { cat: "Music",     ill: "trumpet",    title: "Last Night of the Proms",
      body: "Every year people wave flags, sing loudly and pretend they remember the words to old British songs." },
    { cat: "Invention", ill: "tv",         title: "The TV — invented in 1925",
      body: "John Logie Baird, from Scotland, showed the first moving television picture. Cat videos took longer." },
    { cat: "People",    ill: "lamp",       title: "Florence Nightingale, lamp lady",
      body: "She basically invented modern nursing in the 1850s, walking the wards at night with her lantern." },

    /* ===== NEW (33–45) ===== */
    { cat: "Place",     ill: "tube",       title: "There are over 6,000 castles!",
      body: "Britain has more castles per square mile than almost anywhere on Earth. Every other hill seems to have one." },
    { cat: "Invention", ill: "computer",   title: "The first computer? Bletchley Park",
      body: "During WWII, codebreakers in Buckinghamshire built Colossus — the world's first programmable computer." },
    { cat: "Animal",    ill: "raven",      title: "Loch Ness has a famous monster",
      body: "Nessie is said to live in a deep Scottish lake. Nobody has ever caught one… but tourists keep looking." },
    { cat: "Food",      ill: "pie",        title: "Yorkshire puddings aren't pudding",
      body: "They are giant, fluffy, savoury batter cups. You fill them with gravy. Don't try them with custard." },
    { cat: "People",    ill: "scroll",     title: "Beatrix Potter & her bunnies",
      body: "She wrote and drew Peter Rabbit in the Lake District, then bought 14 farms to save the countryside." },
    { cat: "Place",     ill: "stones",     title: "Wales has the longest place name",
      body: "Llanfair­pwllgwyngyll­gogerychwyrn­drobwllllan­tysiliogogo­goch is a real Welsh village. Try ordering a train ticket!" },
    { cat: "Music",     ill: "guitar",     title: "The Rolling Stones still rock",
      body: "This British band has been touring since 1962. That's older than most grannies." },
    { cat: "Invention", ill: "phone",      title: "The traffic light, 1868",
      body: "London put up the world's first traffic light outside Parliament — to manage horses. It exploded. They tried again later." },
    { cat: "People",    ill: "pencil",     title: "JK Rowling on a napkin",
      body: "Harry Potter was first sketched on a train napkin between Manchester and London. Magical." },
    { cat: "Animal",    ill: "finch",      title: "Puffins on Welsh cliffs",
      body: "Skomer Island is packed with thousands of orange-beaked puffins every summer. They look like tiny grumpy pirates." },
    { cat: "Place",     ill: "lake",       title: "The White Cliffs of Dover",
      body: "On England's south coast, chalk cliffs gleam white above the sea. They're made from millions of tiny ancient sea creatures." },
    { cat: "Food",      ill: "tea",        title: "Cream tea has rules",
      body: "Scones, jam, cream. In Devon, cream goes on first. In Cornwall, jam first. Wars have nearly started over this." },
    { cat: "Invention", ill: "mower",      title: "The cat's eyes on roads",
      body: "Percy Shaw invented those reflective road studs in 1934 — after a cat helped him see in the fog. Good cat." },
  ],

  /* ===== quiz questions — 12 ===== */
  quiz: [
    { q: "Which of these is NOT part of the United Kingdom?",
      options: ["England", "Scotland", "Republic of Ireland", "Wales"],
      answer: 2,
      explain: "The Republic of Ireland is its own country! The UK is England, Scotland, Wales and Northern Ireland." },
    { q: "What is the capital of Scotland?",
      options: ["Glasgow", "Edinburgh", "Aberdeen", "Inverness"],
      answer: 1,
      explain: "Edinburgh — home of an extinct volcano AND a giant castle on a rock." },
    { q: "Great Britain is...",
      options: ["A country", "An island", "A city", "A train"],
      answer: 1,
      explain: "Great Britain is the BIG island holding England, Scotland and Wales." },
    { q: "Who wrote Charlie and the Chocolate Factory?",
      options: ["JK Rowling", "Roald Dahl", "Beatrix Potter", "Shakespeare"],
      answer: 1,
      explain: "Roald Dahl — wrote almost all his books in a tiny shed in his garden!" },
    { q: "What is the capital of Wales?",
      options: ["Swansea", "Belfast", "Cardiff", "Bangor"],
      answer: 2,
      explain: "Cardiff! Wales also has more sheep than people, just so you know." },
    { q: "Which British scientist invented the World Wide Web?",
      options: ["Isaac Newton", "Tim Berners-Lee", "Charles Darwin", "Stephen Hawking"],
      answer: 1,
      explain: "Sir Tim Berners-Lee, in 1989. You're using his invention right now!" },
    { q: "The British Isles includes...",
      options: ["Just England", "Only the UK", "The UK AND the Republic of Ireland", "Just islands with castles"],
      answer: 2,
      explain: "Yes! British Isles = UK + Republic of Ireland + lots of smaller islands." },
    { q: "What's the actual name of the Big Ben tower?",
      options: ["Elizabeth Tower", "Victoria Spire", "Westminster Steeple", "King's Clock"],
      answer: 0,
      explain: "Elizabeth Tower! Big Ben is the bell INSIDE it." },

    /* ===== NEW (9–12) ===== */
    { q: "Which famous band came from Liverpool?",
      options: ["The Rolling Stones", "Queen", "The Beatles", "Coldplay"],
      answer: 2,
      explain: "The Beatles! Four lads who became the most famous band on the planet." },
    { q: "What is the capital of Northern Ireland?",
      options: ["Dublin", "Cork", "Derry", "Belfast"],
      answer: 3,
      explain: "Belfast! Dublin is in the Republic of Ireland — different country." },
    { q: "How old (roughly) is Stonehenge?",
      options: ["500 years", "1,000 years", "5,000 years", "10 years"],
      answer: 2,
      explain: "About 5,000 years old — older than the Egyptian pyramids!" },
    { q: "Which Welsh animal outnumbers people 3 to 1?",
      options: ["Cows", "Dragons", "Sheep", "Squirrels"],
      answer: 2,
      explain: "Sheep! Wales has roughly 3 sheep for every person." },
  ],

  /* ===== timeline ===== */
  timeline: [
    { year: "~3000 BC", ill: "stones", title: "Stonehenge stands up",
      body: "Ancient people drag huge stones across the land and arrange them in a circle. We still don't fully know why!" },
    { year: "43 AD", ill: "scroll", title: "The Romans invade",
      body: "They build roads, walls and very fancy baths. Many roads they made are still used today." },
    { year: "1066", ill: "crown", title: "Battle of Hastings",
      body: "William the Conqueror crosses the channel and changes English forever. Lots of new words appear in the language." },
    { year: "1215", ill: "scroll", title: "The Magna Carta",
      body: "King John signs a famous document saying even kings have to follow rules. Big day for fairness." },
    { year: "1599", ill: "shakespeare", title: "Shakespeare's Globe opens",
      body: "London gets a wooden theatre where the bard puts on his plays. People throw vegetables if it's bad." },
    { year: "1707", ill: "crown", title: "Great Britain forms",
      body: "Scotland joins with England and Wales to make one big kingdom: Great Britain." },
    { year: "1801", ill: "crown", title: "The United Kingdom begins",
      body: "Ireland joins the union and the country becomes the United Kingdom." },
    { year: "1829", ill: "train", title: "The Rocket steams off",
      body: "George Stephenson's locomotive zooms along at 30mph. The age of trains begins." },
    { year: "1863", ill: "tube", title: "London Underground opens",
      body: "The world's first underground railway. Mind the gap!" },
    { year: "1928", ill: "penicillin", title: "Penicillin discovered",
      body: "Alexander Fleming spots mould killing bacteria in his lab. Medicine is changed forever." },
    { year: "1953", ill: "crown", title: "Queen Elizabeth II crowned",
      body: "She'll go on to reign for 70 years — the longest of any British monarch." },
    { year: "1966", ill: "olympics", title: "England wins the World Cup",
      body: "Football comes home (just the once)." },
    { year: "1989", ill: "web", title: "The web is invented",
      body: "Tim Berners-Lee, working at CERN, designs the World Wide Web. Hello, internet." },
    { year: "2012", ill: "olympics", title: "London Olympics",
      body: "The whole world comes to London for the Games. The opening ceremony has the Queen, Mr. Bean and a lot of fireworks." },
    { year: "Today", ill: "crown", title: "Four countries, one kingdom",
      body: "England, Scotland, Wales and Northern Ireland — different flags, different accents, one team." }
  ]
};
